FROM maven:3.9-openjdk-17-slim AS build
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN mvn clean package

FROM openjdk:17-slim
WORKDIR /app
COPY --from=build /build/target/p2p-1.0-SNAPSHOT-shaded.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]

